swagger: '2.0'
basePath: /v0
host: api.hnpwa.com
schemes:
  - https
info:
  contact:
    name: Jim Northrup
    email: jim@vsiwest.com
  description: use this to generate from swagger tools
  termsOfService: tbd
  title: hnpwa
  version: '0'
consumes:
  - application/json
produces:
  - application/json
paths:
  '/news/{page}.json':
    get:
      parameters:
        - in: path
          name: page
          required: true
          type: integer
          minimum: 1
          maximum: 10
      responses:
        '200':
          description: tbd
          schema:
            type: array
            items:
              $ref: '#/definitions/feedItem'
  '/newest/{page}.json':
    get:
      parameters:
        - in: path
          name: page
          required: true
          type: integer
          minimum: 1
          maximum: 12
      responses:
        '200':
          description: tbd
          schema:
            type: array
            items:
              $ref: '#/definitions/feedItem'
  '/ask/{page}.json':
    get:
      parameters:
        - in: path
          name: page
          required: true
          type: integer
          minimum: 1
          maximum: 2
      responses:
        '200':
          description: tbd
          schema:
            type: array
            items:
              $ref: '#/definitions/feedItem'
  '/show/{page}.json':
    get:
      parameters:
        - in: path
          name: page
          required: true
          type: integer
          minimum: 1
          maximum: 1
      responses:
        '200':
          description: tbd
          schema:
            type: array
            items:
              $ref: '#/definitions/feedItem'
  '/item/{id}.json':
    get:
      parameters:
        - in: path
          name: id
          required: true
          type: integer
          minimum: 1
      responses:
        '200':
          $ref: '#/definitions/item'
  '/user/{id}.json':
    get:
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          $ref: '#/definitions/user'
definitions:
  user:
    type: object
    required:
      - created_time
      - created
      - id
      - karma
    properties:
      created_time:
        type: integer
        default: 0
      created:
        type: string
        default: ''
        pattern: ^(.*)$
      id:
        type: string
        default: ''
        pattern: ^(.*)$
      karma:
        type: integer
        default: 0
  item:
    type: object
    required:
      - id
      - title
      - user
      - time
      - time_ago
      - url
    properties:
      id:
        type: integer
        default: 0
      title:
        type: string
        default: ''
        pattern: ^(.*)$
      points:
        type: integer
        default: 0
      user:
        type: string
        default: ''
        pattern: ^(.*)$
      time:
        type: integer
        default: 0
      time_ago:
        type: string
        default: ''
        pattern: ^(.*)$
      type:
        type: string
        default: ''
        pattern: ^(.*)$
      content:
        type: string
        default: ''
        pattern: ^(.*)$
      comments:
        type: array
        items:
          $ref: '#/definitions/item'
      comments_count:
        type: integer
        default: 0
      url:
        type: string
        default: ''
        pattern: ^(.*)$
      domain:
        type: string
        default: ''
        pattern: ^(.*)$
  feedItem:
    type: object
    properties:
      id:
        type: integer
      title:
        type: string
      points:
        type: integer
      user:
        type: string
      time:
        type: integer
      time_ago:
        type: string
      comments_count:
        type: integer
      'type':
        type: string
      url:
        type: string
      domain:
        type: string
